spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: DEBUG

integration:
  transaction-property:
    base-url: "http://localhost:8083/webhook/transaction"
  pay-out-property:
    base-url: "http://localhost:8083/webhook/payout"