spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  r2dbc:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    url: ${FLYWAY_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  profiles:
    active: mock

server:
  port: 8082

integration:
  transaction-property:
    base-url: "http://localhost:8083/webhook/transaction"
  pay-out-property:
    base-url: "http://localhost:8083/webhook/payout"