apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-provider-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-provider
  template:
    metadata:
      labels:
        app: payment-provider
    spec:
      containers:
        - name: payment-provider
          image: "glaptev8/payment-provider:v0.0"
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "r2dbc:pool:postgres://postgres-service:5432/payment_provider"
            - name: FLYWAY_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/payment_provider"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: payment-provider-service
spec:
  selector:
    app: payment-provider
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer